# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: install dependencies
    - run: |
       rm -rf node-modules/
       npm i
       npm run build --if-present
       npm test
      env: 
        ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
        AUTH_EMAIL: ${{secrets.FACEBOOK_CLIENT_ID}}
        AUTH_PASS: ${{secrets.AUTH_PASS}}
        GROUP_TOKEN_SECRET: ${{secrets.GROUP_TOKEN_SECRET}}
        GOOGLE_CALLBACK_URL: ${{secrets.GOOGLE_CALLBACK_URL}}
        BASE_URL: ${{secrets.BASE_URL}}
        JWT_SECRET: ${{secrets.JWT_SECRET}}
        FACEBOOK_ID: ${{secrets.FACEBOOK_ID}}
        FACEBOOK_SECRET: ${{secrets.FACEBOOK_SECRET}}
        GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
        GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
        CLOUDINARY_NAME: ${{secrets.CLOUDINARY_NAME}}
        CLOUDINARY_API_KEY: ${{secrets.CLOUDINARY_API_KEY}}
        CLOUDINARY_SECRET: ${{secrets.CLOUDINARY_SECRET}}
        
  deploy:
       runs-on: ${{matrix.os}}
       needs: [build]
       steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.12.12 
          with:
           heroku_api_key: ${{secrets.HEROKU_API_KEY}}
           heroku_app_name: "YOUR APP's NAME" #Must be unique in Heroku
           heroku_email: "YOUR EMAIL"

